### ISSUE TITLE
Enter doesn't work after setData() is called with empty string

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5-enter#49] opened 2017-12-10 00:15 UTC
After `editor.setData("")` is executed, enter stops working. By "not working" I mean that pressing enter doesn't make a newline. No error in the console. Interestingly change event is still triggered.

If I don't call .setData() at all (so editor stays empty), enter works. After calling .setData() with non-empty string, enter works as well.

Testing this on alpha 2 with Balloon editor.

**Comment by Reinmar** [comment] 2018-01-09 09:50
We're very sorry for the late answer. We somehow missed this ticket.

Anyway, the issue is caused by lack of paragraphs in the editor after setting data in that way. There's a ticket for that already: https://github.com/ckeditor/ckeditor5/issues/744. 

I'll close this ticket since the root cause of this issue is somewhere else. Feel free to comment further there or there.

**Closed by Reinmar** 2018-01-09 09:50 UTC
