### ISSUE TITLE
[Android] enter doesn't work after phoned turned off

### ISSUE THREAD

**Issue by iEgit** [ckeditor/ckeditor5-enter#48] opened 2017-10-17 13:03 UTC
1. enter some text
2. turn off the phone
3. turn on the phone

**Actual result**: carriage is on one line lower, enter doesn't work
**Expected result**: carriage is on the same line lower, enter does work
**Reproduced on**: Samsung 4.5, Samsung 7.0, LG 6.0, xiaomi 6.0

**Comment by Mgsy** [comment] 2017-10-17 14:42
Unfortunately, I'm not able to reproduce this issue on Nexus (Android 4.4.4) and LG K8 (Android 7.0). Please, let me know if my steps are correct:

1. Open the editor on the device.
2. Type some text.
3. Press `power` button on the phone to block it and turn off the screen.
4. Repeat step 3 to unblock the phone and turn on the screen.

**Comment by Reinmar** [comment] 2017-10-17 15:20
Just like in the other ticket – you may be testing on different browsers.

Although, it's scary that you can get so many different results ;|

**Comment by f1ames** [comment] 2018-07-04 13:40
I have rechecked this issue on Android `6.0.1` and `8.0.0` with latest Chrome (`67`) and a `WebView` and was not able to reproduce it. Since we support [all officially supported Android versions](https://en.wikipedia.org/wiki/Android_version_history) which ATM are `Android 6+` I'm closing this issue.

@iEgit if you have some new discoveries or was able to check this issue on newer versions please drop a comment too.

**Closed by f1ames** 2018-07-04 13:40 UTC
Labels: resolution:invalid, status:pending, type:bug
