### ISSUE TITLE
[Android] The first word gets duplicated while line-break

### ISSUE THREAD

**Issue by iEgit** [ckeditor/ckeditor5-enter#47] opened 2017-10-17 12:47 UTC
1 Enter a word
3 Put carriage to the beggining of the word
4 Press enter

**Actual result**: inserted line-break and the word gets duplicated
**Expected result**: inserted line-break 
Video: https://yadi.sk/i/Ab1Y2ArO3NEeWC

**Reproduced in**  Nexus 6/7.0

I've investigated this issue and turned out the problem is that for some reason android moves carriage right right after pressing enter on keyboard. But the selection observer knew nothing about this movement and for some reason the word gets duplicated. The workaround we used was to place the carriage back to where the selection observes thinks it should be and then do

**Comment by Mgsy** [comment] 2017-10-17 13:55
Hello, @iEgit, thanks for providing the video, it's really helpful. I checked your issue and I wasn't able to achieve the result which you've described, but got a similar one. 

After putting the caret at the beginning of the word and pressing <kbd>Enter</kbd>, the word moves to the next line, but the selection doesn't change, so we have:
```
{}
word
```
 If I press <kbd>Enter</kbd> once again, the word duplicates and the selection is correct, so the result is
```
{}word
word
```
Further pressing <kbd>Enter</kbd> works correct. I was testing it on Nexus 7.

Could I ask you to provide us more details about your CKEditor? Which plugins do you use, what kind of build do you have (classic/inline/balloon or custom)?

**Comment by Reinmar** [comment] 2017-10-17 14:13
Just a small note – this can, unfortunately, be affected by things like a used keyboard and language setting.

Basically, in Android, all input is IME-based. This has some merit but means that there's [no key code in `keydown` events](https://bugs.chromium.org/p/chromium/issues/detail?id=118639).

We'll need to work on a completely different approach for Android. We may even extend it to other environments if it will look good.

**Comment by iEgit** [comment] 2017-10-17 14:14
Sure, here is our set up code
```js

import 'mutationobserver-shim';
import 'babel-polyfill';
import './android-polyfill';

import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import EssentialsPlugin from '@ckeditor/ckeditor5-presets/src/essentials';
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
import UnderlinePlugin from '@ckeditor/ckeditor5-basic-styles/src/underline';
import BlockquotePlugin from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import ListPlugin from '@ckeditor/ckeditor5-list/src/list';
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import HeadingPlugin from '@ckeditor/ckeditor5-heading/src/heading';
import LinethroughPlugin from './ckeditor5-linethrough/src/linethrough';

import ImagePlugin from './ckeditor5-image/src/image';
import CheckboxPlugin from './ckeditor5-checkbox/src/checkbox'; // our custom checkbox plugin

import TextAlignmentPlugin from './ckeditor-textalignment'; // our custom text alignment plugin
import AutoformatPlugin from '@ckeditor/ckeditor5-autoformat/src/autoformat';


class Editor extends ClassicEditorBase {}

Editor.build = {
    plugins: [
        AutoformatPlugin,
        BlockquotePlugin,
        BoldPlugin,
        ItalicPlugin,
        UnderlinePlugin,
        CheckboxPlugin,
        EssentialsPlugin,
        HeadingPlugin,
        ImagePlugin,
        ListPlugin,
        ParagraphPlugin,
        TextAlignmentPlugin,
        LinethroughPlugin
    ]
};

Editor.create(document.querySelector('#editor'))

```

**Comment by Reinmar** [comment] 2017-10-17 14:18
Out of curiosity – why did you load `mutationobserver-shim` and `./android-polyfill`? What do you need to polyfill in which Android browsers?

**Comment by iEgit** [comment] 2017-10-17 14:20
As far as I remember this was for Android 4.4

**Comment by Reinmar** [comment] 2017-10-17 14:31
Did those polyfills help? I wonder how far back in time we could go with Android's browser support.

**Comment by iEgit** [comment] 2017-10-17 14:46
Yes, they did. It depends on the features you use. If you want to support Android 4.4 it some es6 features should be polyfilled.

**Comment by Mgsy** [comment] 2017-10-17 14:53
@iEgit, I added this issue to the umbrella ticket, which was created to sum up all known Android-related issues. You can follow it here - https://github.com/ckeditor/ckeditor5/issues/614 - and easily observe the progress of our work.

**Comment by f1ames** [comment] 2018-06-22 14:35
> I checked it also on LG K8 (Android 7.0, Chrome) and it works properly.

I wasn't able to reproduce it on `Huawei MediaPad M5` device (`Android 8`, `Chrome`) too, works fine.

`Android 4.4.4` is pretty old (2013) and it's not longer supported. The oldest supported version ATM is `Android 5` (see https://en.wikipedia.org/wiki/Android_version_history) so I guess we should be focusing on latest versions. Not sure though if we should close this ticket, label it in some special way or leave for now as a reference? WDYT @Reinmar @Mgsy

**Comment by f1ames** [comment] 2018-07-04 13:17
I have rechecked this issue on Android `6.0.1` and `8.0.0` with latest Chrome (`67`) and a `WebView` and was not able to reproduce it. Since we support [all officially supported Android versions](https://en.wikipedia.org/wiki/Android_version_history) which ATM are `Android 6+` I'm closing this issue.

@iEgit if you have some new discoveries or was able to check this issue on newer versions please drop a comment too.

**Closed by f1ames** 2018-07-04 13:17 UTC
Labels: status:confirmed, type:bug

**Comment by racheldaitch** [comment] 2019-05-09 16:37
Hi,
What is about this bug? My customer left my product because this problem :(. Any suggesions?
Or - do youy know another text editor for mobile without this problem?
Thanks.

**Comment by Reinmar** [comment] 2019-05-20 08:19
As commented by @f1ames this bug does not occur in the supported versions of Android. We do not plan to support older versions.
